// mydly-vue/src/App.vue
<template>
	<div
		id="app"
		class="bg-primary-dark min-h-screen px-10 py-5 text-primary-white flex flex-col justify-between"
	>
		<Navbar />
		<router-view></router-view>
		<Footer />
	</div>
</template>

<script>
import Navbar from './components/Navbar'
import Footer from './components/Footer'

export default {
	name: 'App',
	components: {
		Navbar,
		Footer,
	},
}
</script>

<style></style>

// mydly-react/src/App.jsx
import { Switch } from 'react-router-dom'

import routes from './routes'
import Navbar from './components/Navbar'
import Footer from './components/Footer'

const App = () => (
	<div className='bg-primary-dark min-h-screen px-10 py-5 text-primary-white flex flex-col justify-between'>
		<Navbar />
		<Switch>
			{routes.map(({ path, component, RouteType }, id) => (
				<RouteType key={id} path={path} exact component={component} />
			))}
		</Switch>
		<Footer />
	</div>
)

export default App
