// mydly-vue/src/components/Input/index.vue
<template>
	<input
		:type="type"
		:placeholder="placeholder"
		:value="value"
		v-on="$listeners"
		@input="$emit('update', $event.target.value)"
		class="shadow appearance-none bg-primary-gray w-full py-4 px-3 mb-4
             text-primary-white leading-tight focus:outline-none focus:shadow-outline rounded-none"
		:class="className"
	/>
</template>

<script>
export default {
	props: {
		type: { type: String },
		placeholder: String,
		className: String,
		value: { type: String, required: false, default: '' },
	},
	model: {
		prop: 'value',
		event: 'update',
	},
}
</script>

<style></style>

// mydly-react/src/components/Input/index.jsx
import React from 'react'

const Input = (prop) => {
	return (
		<input
			{...prop}
			placeholder={prop.placeholder}
			autoComplete='off'
			className={`shadow appearance-none bg-primary-gray w-full py-4 px-3 mb-4
             text-primary-white leading-tight focus:outline-none focus:shadow-outline rounded-none ${prop.className}`}
			type={prop.type}
		/>
	)
}

export default Input
